In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("편의시설 변경 버전.csv", encoding='cp949')

In [3]:
df['보건'] = df['병원'] + df['약국'] + df['의원']

In [4]:
df = df[['법정동명','병원','약국','의원', '보건']]

## 인덱스 1씩 미루기

In [5]:
df['dong_id'] = df.index + 1
df

    법정동명  병원  약국   의원   보건  dong_id
0    청운동   0   0    0    0        1
1    신교동   0   0    1    1        2
2    궁정동   0   0    0    0        3
3    효자동   0   0    0    0        4
4    창성동   0   1    3    4        5
..   ...  ..  ..  ...  ...      ...
460  둔촌동   0  16   18   34      461
461  암사동   0  23   69   92      462
462  성내동   5  40  125  170      463
463  천호동   6  58  141  205      464
464  강일동   0  13   28   41      465

[465 rows x 6 columns]

In [6]:
df = df.drop(axis=1, columns=['법정동명'])

In [7]:
df

     병원  약국   의원   보건  dong_id
0     0   0    0    0        1
1     0   0    1    1        2
2     0   0    0    0        3
3     0   0    0    0        4
4     0   1    3    4        5
..   ..  ..  ...  ...      ...
460   0  16   18   34      461
461   0  23   69   92      462
462   5  40  125  170      463
463   6  58  141  205      464
464   0  13   28   41      465

[465 rows x 5 columns]

In [8]:
df.to_csv("final_dataset/health.csv", encoding='cp949', index=0)