In [1]:
import pandas as pd

In [25]:
df = pd.read_csv("dataset/서울특별시_전월세가_2023.csv", )
df1 = pd.read_csv("dataset/서울시 부동산 전월세가 정보_2022.csv", encoding="cp949")
# df2 = pd.read_csv("dataset/서울시 부동산 전월세가 정보_2021.csv", encoding="cp949")
# df = pd.read_csv("dataset/서울특별시_전월세가_2020.csv")
# df = pd.read_csv("dataset/서울특별시_전월세가_2019.csv")

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3392\2794465152.py:2: DtypeWarning: Columns (18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("dataset/서울시 부동산 전월세가 정보_2022.csv", encoding="cp949")

In [26]:
df1.columns

Index(['접수연도', '자치구코드', '자치구명', '법정동코드', '법정동명', '지번구분', '지번구분명', '본번', '부번',
       '층', '계약일', '전월세 구분', '임대면적(㎡)', '보증금(만원)', '임대료(만원)', '건물명', '건축년도',
       '건물용도', '계약기간', '신규갱신여부', '계약갱신권사용여부', '종전 보증금', '종전 임대료'],
      dtype='object')

In [27]:
df.columns

Index(['접수년도', '자치구코드', '자치구명', '법정동코드', '법정동명', '지번구분코드', '지번구분', '본번', '부번',
       '층', '계약일', '전월세구분', '임대면적', '보증금(만원)', '임대료(만원)', '건물명', '건축년도',
       '건물용도', '계약기간', '신규계약구분', '갱신청구권사용', '종전보증금', '종전임대료'],
      dtype='object')

In [29]:
df1 = df1[['접수연도', '자치구명','법정동명','본번','부번','층','전월세 구분','임대면적(㎡)','보증금(만원)','임대료(만원)','건물명','건축년도','건물용도']]
# df2 = df2[['접수연도', '자치구명','법정동명','본번','부번','층','전월세 구분','임대면적(㎡)','보증금(만원)','임대료(만원)','건물명','건축년도','건물용도']]
df = df[['접수년도', '자치구명','법정동명','본번','부번','층','전월세구분','임대면적','보증금(만원)','임대료(만원)','건물명','건축년도','건물용도']]

In [30]:
df1 = df1.rename(columns={'전월세 구분': '전월세구분'})
# df2 = df2.rename(columns={'전월세 구분': '전월세구분'})

df = df.rename(columns={'임대면적': '임대면적(㎡)'})
df = df.rename(columns={'접수년도': '접수연도'})

In [31]:
new = pd.concat([df,df1])

In [34]:
new.isnull().sum()

접수연도            0
자치구명           33
법정동명           33
본번         247431
부번         247431
층          247699
전월세구분           0
임대면적(㎡)         0
보증금(만원)         0
임대료(만원)         0
건물명        247724
건축년도        15750
건물용도            0
dtype: int64

In [36]:
new = new.dropna()

In [37]:
new

,접수연도,자치구명,법정동명,본번,부번,층,전월세구분,임대면적(㎡),보증금(만원),임대료(만원),건물명,건축년도,건물용도
0,2023,마포구,노고산동,1.0,1.0,8.0,월세,31.12,10000,40,\t(1-1)\t,1998.0,오피스텔
1,2023,마포구,노고산동,1.0,1.0,5.0,월세,33.66,10000,55,\t(1-1)\t,1998.0,오피스텔
2,2023,마포구,노고산동,1.0,1.0,9.0,전세,33.66,21000,0,\t(1-1)\t,1998.0,오피스텔
3,2023,용산구,원효로2가,1.0,0.0,9.0,전세,71.67,23900,0,\t(1)\t,1990.0,오피스텔
4,2023,마포구,노고산동,1.0,1.0,9.0,전세,41.04,22000,0,\t(1-1)\t,1998.0,오피스텔
...,...,...,...,...,...,...,...,...,...,...,...,...,...
376133,2022,중구,남산동2가,42.0,0.0,2.0,월세,62.64,10000,50,남산퍼시픽,2003.0,아파트
376138,2022,마포구,아현동,737.0,0.0,14.0,월세,31.09,1500,70,마포 에스케이 허브 블루,2006.0,오피스텔
376167,2022,송파구,가락동,45.0,3.0,3.0,월세,50.39,1500,60,무지개빌라,1991.0,연립다세대
376174,2022,종로구,동숭동,4.0,125.0,3.0,월세,51.95,2500,35,(4-125),1998.0,연립다세대
376175,2022,도봉구,방학동,694.0,27.0,5.0,월세,57.88,17700,20,흥진아트빌(694-27),2003.0,연립다세대

In [38]:
new = new[~new['건물명'].str.contains(r'\t\(\d+(-\d+)?\)\t')]

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3392\1938879151.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  new = new[~new['건물명'].str.contains(r'\t\(\d+(-\d+)?\)\t')]

In [40]:
new['본번'] = new['본번'].astype('int')
new['부번'] = new['부번'].astype('int')
new['층'] = new['층'].astype('int')
new['건축년도'] = new['건축년도'].astype('int')

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3392\1560085201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['본번'] = new['본번'].astype('int')
C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3392\1560085201.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['부번'] = new['부번'].astype('int')
C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3392\1560085201.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['층'] = new['층'].astype('int')
C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3392\1560085201.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['건축년도'] = new['건축년도'].astype('int')

In [41]:
new['지번주소'] = '서울특별시 ' + new['자치구명']+' '+new['법정동명']+' '+new['본번'].astype('str')+'-'+new['부번'].astype('str')

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_3392\3898784247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['지번주소'] = '서울특별시 ' + new['자치구명']+' '+new['법정동명']+' '+new['본번'].astype('str')+'-'+new['부번'].astype('str')

In [42]:
new

,접수연도,자치구명,법정동명,본번,부번,층,전월세구분,임대면적(㎡),보증금(만원),임대료(만원),건물명,건축년도,건물용도,지번주소
46,2023,중랑구,묵동,386,0,3,전세,84.71,46000,0,금호어울림,2003,아파트,서울특별시 중랑구 묵동 386-0
53,2023,중랑구,묵동,386,0,4,전세,101.97,46500,0,금호어울림,2003,아파트,서울특별시 중랑구 묵동 386-0
56,2023,종로구,명륜3가,1,1028,1,월세,83.37,1000,85,(1-1028),1976,연립다세대,서울특별시 종로구 명륜3가 1-1028
83,2023,강남구,자곡동,655,0,2,월세,19.97,5000,42,\t강남 푸르지오시티 2차(PRUGIO CITYⅡ)\t,2014,오피스텔,서울특별시 강남구 자곡동 655-0
105,2023,은평구,신사동,1,103,5,월세,56.02,3000,50,(1-103),2011,연립다세대,서울특별시 은평구 신사동 1-103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376133,2022,중구,남산동2가,42,0,2,월세,62.64,10000,50,남산퍼시픽,2003,아파트,서울특별시 중구 남산동2가 42-0
376138,2022,마포구,아현동,737,0,14,월세,31.09,1500,70,마포 에스케이 허브 블루,2006,오피스텔,서울특별시 마포구 아현동 737-0
376167,2022,송파구,가락동,45,3,3,월세,50.39,1500,60,무지개빌라,1991,연립다세대,서울특별시 송파구 가락동 45-3
376174,2022,종로구,동숭동,4,125,3,월세,51.95,2500,35,(4-125),1998,연립다세대,서울특별시 종로구 동숭동 4-125
376175,2022,도봉구,방학동,694,27,5,월세,57.88,17700,20,흥진아트빌(694-27),2003,연립다세대,서울특별시 도봉구 방학동 694-27

In [43]:
new['지번주소'].to_csv('지번주소.csv', index=False)