In [159]:
import pandas as pd

In [160]:
df1 = pd.read_csv('dataset/서울교통공사 지하철역 주소 및 전화번호 정보.csv', encoding='cp949')

In [162]:
df1 = df1[['호선','역명','도로명주소']]
df1['도로명주소1'] = df1['도로명주소']

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_6540\281250067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['도로명주소1'] = df1['도로명주소']

지하철역 주소 서울시만 뽑고, 법정동만 추출  
지하철역 갯수 288 -> 273

In [163]:
df1 = df1[df1['도로명주소'].str.startswith('서울특별시')]
df1['도로명주소'] = df1['도로명주소'].str.extract('\(([^)]+)\)')
df1 = df1.rename(columns={'도로명주소': '법정동', '도로명주소1' : '도로명주소'})
df1

      호선           역명      법정동                        도로명주소
0    2호선           봉천      봉천동  서울특별시 관악구 남부순환로 지하1721(봉천동)
1    1호선           서울  남대문로 5가   서울특별시 중구 세종대로 지하2(남대문로 5가)
2    1호선           시청       정동      서울특별시 중구 세종대로 지하101(정동)
3    1호선           종각     종로1가      서울특별시 종로구 종로 지하55(종로1가)
4    1호선         종로3가     종로3가     서울특별시 종로구 종로 지하129(종로3가)
..   ...          ...      ...                          ...
283  9호선         송파나루      방이동   서울특별시 송파구 백제고분로 지하446(방이동)
284  9호선         한성백제      방이동    서울특별시 송파구 위례성대로 지하29(방이동)
285  9호선  올림픽공원(한국체대)      방이동   서울특별시 송파구 양재대로 지하1233(방이동)
286  9호선         둔촌오륜      둔촌동    서울특별시 강동구 강동대로 지하303(둔촌동)
287  9호선       중앙보훈병원      둔촌동     서울특별시 강동구 동남로 지하625(둔촌동)

[273 rows x 4 columns]

In [164]:
df1

      호선           역명      법정동                        도로명주소
0    2호선           봉천      봉천동  서울특별시 관악구 남부순환로 지하1721(봉천동)
1    1호선           서울  남대문로 5가   서울특별시 중구 세종대로 지하2(남대문로 5가)
2    1호선           시청       정동      서울특별시 중구 세종대로 지하101(정동)
3    1호선           종각     종로1가      서울특별시 종로구 종로 지하55(종로1가)
4    1호선         종로3가     종로3가     서울특별시 종로구 종로 지하129(종로3가)
..   ...          ...      ...                          ...
283  9호선         송파나루      방이동   서울특별시 송파구 백제고분로 지하446(방이동)
284  9호선         한성백제      방이동    서울특별시 송파구 위례성대로 지하29(방이동)
285  9호선  올림픽공원(한국체대)      방이동   서울특별시 송파구 양재대로 지하1233(방이동)
286  9호선         둔촌오륜      둔촌동    서울특별시 강동구 강동대로 지하303(둔촌동)
287  9호선       중앙보훈병원      둔촌동     서울특별시 강동구 동남로 지하625(둔촌동)

[273 rows x 4 columns]

In [165]:
df1.to_csv('subway.csv', index=False)