In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('dataset/서울교통공사 지하철역 주소 및 전화번호 정보.csv', encoding='cp949')

In [3]:
df1 = df1[['호선','역명','도로명주소']]
df1['도로명주소1'] = df1['도로명주소']

지하철역 주소 서울시만 뽑고, 법정동만 추출  
지하철역 갯수 288 -> 273

In [4]:
df1 = df1[df1['도로명주소'].str.startswith('서울특별시')]
df1['도로명주소'] = df1['도로명주소'].str.extract('\(([^)]+)\)')
df1 = df1.rename(columns={'도로명주소': '법정동', '도로명주소1' : '도로명주소'})
df1

      호선           역명      법정동                        도로명주소
0    2호선           봉천      봉천동  서울특별시 관악구 남부순환로 지하1721(봉천동)
1    1호선           서울  남대문로 5가   서울특별시 중구 세종대로 지하2(남대문로 5가)
2    1호선           시청       정동      서울특별시 중구 세종대로 지하101(정동)
3    1호선           종각     종로1가      서울특별시 종로구 종로 지하55(종로1가)
4    1호선         종로3가     종로3가     서울특별시 종로구 종로 지하129(종로3가)
..   ...          ...      ...                          ...
283  9호선         송파나루      방이동   서울특별시 송파구 백제고분로 지하446(방이동)
284  9호선         한성백제      방이동    서울특별시 송파구 위례성대로 지하29(방이동)
285  9호선  올림픽공원(한국체대)      방이동   서울특별시 송파구 양재대로 지하1233(방이동)
286  9호선         둔촌오륜      둔촌동    서울특별시 강동구 강동대로 지하303(둔촌동)
287  9호선       중앙보훈병원      둔촌동     서울특별시 강동구 동남로 지하625(둔촌동)

[273 rows x 4 columns]

In [5]:
df1

      호선           역명      법정동                        도로명주소
0    2호선           봉천      봉천동  서울특별시 관악구 남부순환로 지하1721(봉천동)
1    1호선           서울  남대문로 5가   서울특별시 중구 세종대로 지하2(남대문로 5가)
2    1호선           시청       정동      서울특별시 중구 세종대로 지하101(정동)
3    1호선           종각     종로1가      서울특별시 종로구 종로 지하55(종로1가)
4    1호선         종로3가     종로3가     서울특별시 종로구 종로 지하129(종로3가)
..   ...          ...      ...                          ...
283  9호선         송파나루      방이동   서울특별시 송파구 백제고분로 지하446(방이동)
284  9호선         한성백제      방이동    서울특별시 송파구 위례성대로 지하29(방이동)
285  9호선  올림픽공원(한국체대)      방이동   서울특별시 송파구 양재대로 지하1233(방이동)
286  9호선         둔촌오륜      둔촌동    서울특별시 강동구 강동대로 지하303(둔촌동)
287  9호선       중앙보훈병원      둔촌동     서울특별시 강동구 동남로 지하625(둔촌동)

[273 rows x 4 columns]

In [7]:
df1[df1['호선'] == '1호선']

     호선            역명      법정동                       도로명주소
1   1호선            서울  남대문로 5가  서울특별시 중구 세종대로 지하2(남대문로 5가)
2   1호선            시청       정동     서울특별시 중구 세종대로 지하101(정동)
3   1호선            종각     종로1가     서울특별시 종로구 종로 지하55(종로1가)
4   1호선          종로3가     종로3가    서울특별시 종로구 종로 지하129(종로3가)
5   1호선          종로5가     종로5가    서울특별시 종로구 종로 지하216(종로5가)
6   1호선           동대문      창신동     서울특별시 종로구 종로 지하302(창신동)
7   1호선           신설동      신설동     서울특별시 동대문구 왕산로 지하1(신설동)
8   1호선           제기동      제기동    서울특별시 동대문구 왕산로 지하93(제기동)
9   1호선  청량리(서울시립대입구)      전농동   서울특별시 동대문구 왕산로 지하205(전농동)
10  1호선           동묘앞      숭인동       서울특별시 종로구 종로 359(숭인동)

In [11]:
df1['station_id'] = df1.index + 1

In [12]:
df1

      호선           역명      법정동                        도로명주소  station_id
0    2호선           봉천      봉천동  서울특별시 관악구 남부순환로 지하1721(봉천동)           1
1    1호선           서울  남대문로 5가   서울특별시 중구 세종대로 지하2(남대문로 5가)           2
2    1호선           시청       정동      서울특별시 중구 세종대로 지하101(정동)           3
3    1호선           종각     종로1가      서울특별시 종로구 종로 지하55(종로1가)           4
4    1호선         종로3가     종로3가     서울특별시 종로구 종로 지하129(종로3가)           5
..   ...          ...      ...                          ...         ...
283  9호선         송파나루      방이동   서울특별시 송파구 백제고분로 지하446(방이동)         284
284  9호선         한성백제      방이동    서울특별시 송파구 위례성대로 지하29(방이동)         285
285  9호선  올림픽공원(한국체대)      방이동   서울특별시 송파구 양재대로 지하1233(방이동)         286
286  9호선         둔촌오륜      둔촌동    서울특별시 강동구 강동대로 지하303(둔촌동)         287
287  9호선       중앙보훈병원      둔촌동     서울특별시 강동구 동남로 지하625(둔촌동)         288

[273 rows x 5 columns]

In [14]:
df1.to_csv('subway.csv', encoding='cp949', index=False)